// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NetCoreVue.Data;
using System;

namespace NetCoreVue.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NetCoreVue.Models.AccountDetail", b =>
                {
                    b.Property<int>("AccountDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountDetailId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerAccountId");

                    b.Property<int>("DayOfWeekNumber");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<int>("EndTimeInMinutes")
                        .HasColumnName("EndTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("IsVisible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVisible")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StartTimeInMinutes")
                        .HasColumnName("StartTimeInMinutes")
                        .HasColumnType("int");

                    b.HasKey("AccountDetailId")
                        .HasName("PrimaryKey_AccountDetailId");

                    b.HasIndex("CustomerAccountId");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("NetCoreVue.Models.AccountRate", b =>
                {
                    b.Property<int>("AccountRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountRateId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerAccountId");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnName("RatePerHour")
                        .HasColumnType("DECIMAL(6,2)");

                    b.HasKey("AccountRateId")
                        .HasName("PrimaryKey_AccountRateId");

                    b.HasIndex("CustomerAccountId");

                    b.ToTable("AccountRates");
                });

            modelBuilder.Entity("NetCoreVue.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("NetCoreVue.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CourseId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseAbbreviation")
                        .IsRequired()
                        .HasColumnName("CourseAbbreviation")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnName("CourseName")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("CreatedById");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("DeletedById");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("UpdatedById");

                    b.HasKey("CourseId")
                        .HasName("PrimaryKey_CourseId");

                    b.HasIndex("CourseAbbreviation")
                        .IsUnique()
                        .HasName("Course_CourseAbbreviation_UniqueConstraint");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("NetCoreVue.Models.CustomerAccount", b =>
                {
                    b.Property<int>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerAccountId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnName("AccountName")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Comments")
                        .HasColumnName("Comments")
                        .HasColumnType("NVARCHAR(4000)")
                        .HasMaxLength(4000);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("CreatedById");

                    b.Property<bool?>("IsVisible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVisible")
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("UpdatedById");

                    b.HasKey("CustomerAccountId")
                        .HasName("PrimaryKey_CustomerAccountId");

                    b.HasIndex("AccountName")
                        .IsUnique()
                        .HasName("CustomerAccount_AccountName_UniqueConstraint");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("NetCoreVue.Models.InstructorAccount", b =>
                {
                    b.Property<int>("InstructorAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InstructorAccountId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnName("Comments")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<int>("CustomerAccountId")
                        .HasColumnName("CustomerAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<int>("InstructorId")
                        .HasColumnName("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCurrent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsCurrent")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("WageRate")
                        .HasColumnName("WageRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("InstructorAccountId")
                        .HasName("PrimaryKey_InstructorAccounttId");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAccounts");
                });

            modelBuilder.Entity("NetCoreVue.Models.SessionSynopsis", b =>
                {
                    b.Property<int>("SessionSynopsisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SessionSynopsisId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedById");

                    b.Property<bool?>("IsVisible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVisible")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SessionSynopsisName")
                        .IsRequired()
                        .HasColumnName("SessionSynopsisName")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedById");

                    b.HasKey("SessionSynopsisId")
                        .HasName("PrimaryKey_SessionSynopsisId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SessionSynopsisName")
                        .IsUnique()
                        .HasName("SessionSynopsis_SessionSynopsisName_UniqueConstraint");

                    b.HasIndex("UpdatedById");

                    b.ToTable("SessionSynopses");
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovedAt");

                    b.Property<int?>("ApprovedById")
                        .IsRequired();

                    b.Property<int>("CheckedById");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("CreatedById");

                    b.Property<int>("InstructorId");

                    b.Property<DateTime>("MonthAndYear")
                        .HasColumnName("MonthAndYear");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnName("RatePerHour")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("UpdatedById")
                        .HasColumnName("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAndSubmittedAt")
                        .HasColumnName("VerifiedAndSubmittedAt");

                    b.HasKey("TimeSheetId")
                        .HasName("PrimaryKey_TimeSheetId");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InstructorId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheetDetail", b =>
                {
                    b.Property<int>("TimeSheetDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetDetailId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountDetailId");

                    b.Property<DateTime>("DateOfLesson");

                    b.Property<bool?>("IsReplacementInstructor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsReplacementInstructor")
                        .HasDefaultValue(false);

                    b.Property<int>("OfficialTimeInMinutes")
                        .HasColumnName("OfficialTimeInMinutes");

                    b.Property<int>("OfficialTimeOutMinutes")
                        .HasColumnName("OfficialTimeOutMinutes");

                    b.Property<string>("SessionSynopsisNames")
                        .IsRequired()
                        .HasColumnName("SessionSynopsisNames")
                        .HasColumnType("VARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<int>("TimeInInMinutes");

                    b.Property<int>("TimeOutInMinutes");

                    b.Property<int>("TimeSheetId");

                    b.Property<decimal>("WageRatePerHour")
                        .HasColumnName("WageRatePerHour")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("TimeSheetDetailId")
                        .HasName("PrimaryKey_TimeSheetDetailId");

                    b.HasIndex("AccountDetailId");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("TimeSheetDetails");
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheetDetailSignature", b =>
                {
                    b.Property<int>("TimeSheetDetailSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetDetailSignatureId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Signature")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("TimeSheetIDetailId");

                    b.HasKey("TimeSheetDetailSignatureId")
                        .HasName("PrimaryKey_TimeSheetSignatureId");

                    b.HasIndex("TimeSheetIDetailId")
                        .IsUnique();

                    b.ToTable("TimeSheetDetailSignature");
                });

            modelBuilder.Entity("NetCoreVue.Models.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserInfoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LoginUserName")
                        .IsRequired()
                        .HasColumnName("LoginUserName")
                        .HasColumnType("VARCHAR(10)")
                        .HasMaxLength(10);

                    b.HasKey("UserInfoId")
                        .HasName("PrimaryKey_UserInfoId");

                    b.HasIndex("LoginUserName")
                        .IsUnique()
                        .HasName("UserInfo_LoginUserName_UniqueConstraint");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NetCoreVue.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NetCoreVue.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetCoreVue.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NetCoreVue.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreVue.Models.AccountDetail", b =>
                {
                    b.HasOne("NetCoreVue.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("AccountDetails")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreVue.Models.AccountRate", b =>
                {
                    b.HasOne("NetCoreVue.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("AccountRates")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreVue.Models.Course", b =>
                {
                    b.HasOne("NetCoreVue.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetCoreVue.Models.CustomerAccount", b =>
                {
                    b.HasOne("NetCoreVue.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetCoreVue.Models.InstructorAccount", b =>
                {
                    b.HasOne("NetCoreVue.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("InstructorAccounts")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetCoreVue.Models.UserInfo", "Instructor")
                        .WithMany("InstructorAccounts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreVue.Models.SessionSynopsis", b =>
                {
                    b.HasOne("NetCoreVue.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheet", b =>
                {
                    b.HasOne("NetCoreVue.Models.UserInfo", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetCoreVue.Models.UserInfo", "Instructor")
                        .WithMany("TimeSheets")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetCoreVue.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheetDetail", b =>
                {
                    b.HasOne("NetCoreVue.Models.AccountDetail", "AccountDetail")
                        .WithMany("TimeSheetDetails")
                        .HasForeignKey("AccountDetailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetCoreVue.Models.TimeSheet", "TimeSheet")
                        .WithMany("TimeSheetDetails")
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreVue.Models.TimeSheetDetailSignature", b =>
                {
                    b.HasOne("NetCoreVue.Models.TimeSheetDetail", "TimeSheetDetail")
                        .WithOne("TimeSheetDetailSignature")
                        .HasForeignKey("NetCoreVue.Models.TimeSheetDetailSignature", "TimeSheetIDetailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
